### ISSUE TITLE
Can F-SOMV1.exe be open source ?

### ISSUE THREAD

**Issue by tyrael007** [marccasian/KaryML-Framework#1]
Hi, can F-SOMV1.exe be open source ?

**Comment by marccasian** [comment]
Hi @tyrael007, the code is not public as it part of another work prof. Czibula Gabriela research group works on. See: https://www.researchgate.net/publication/316459020_A_Novel_Approach_Using_Fuzzy_Self-Organizing_Maps_for_Detecting_Software_Faults
